[build]
builder = "NIXPACKS"
buildCommand = "cd myapp-backend && pip install -r requirements.txt && npm install && npx prisma generate"

[deploy]
startCommand = "cd myapp-backend && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
