[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt && export PATH=$PATH:/root/.local/bin:/usr/local/bin && npm install && npx prisma generate"
]

[start]
cmd = "gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
