[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "nodejs-18_x"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && npm install && npx prisma generate"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
