[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --timeout 120"
